version: 2

updates:
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"
    groups:
      python-dev-tools:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"
    groups:
      github-actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # NodeJS
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
      timezone: "America/Los_Angeles"
    groups:
      npm-dev:
        dependency-type: "development"
        update-types: ["minor", "patch"]
